name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run buildx and push
        # env:
        #   DOCKER_REPO: ilharp/koishi-docker-test
        run: |
          docker build .
